### ISSUE TITLE
部署时遇到错误 

### ISSUE THREAD

**Issue by yimierxingweisika** [yoooowi/pcr_autocb#20]
{
    "cookie": {
        "session-api": "jeexxxx81oqvobeqxxxxxxx"
    },
    "group": 1310xxxxx,
    "boss_name" : {
        "双足飞龙": 1,
        "巨型哥布林": 1,
        "野性狮鹫": 2,
        "雷雷": 2,
        "陆生树懒": 2,
        "雷电": 3,
        "巨型凶暴兔":3,
        "怒蛇":3,
        "极彩鸟":3,
        "海龙":3,
        "兽人头目": 3,
        "幽灵领主": 3,
        "针刺攀缘花": 3,
        "天空女武神": 3,
        "狂乱魔熊": 4,
        "三战士图腾": 4,
        "暗黑独角兽": 4,
        "独眼巨人": 4,
        "海蛞蝓": 4,
        "泰坦陆龟": 4,
        "魔界人狼": 4,
        "暗黑滴水嘴兽": 4,
        "灵魂角鹿": 4,
        "狸猫首领": 4,
        "巨钳魔蟹":5,
        "双子魔猪": 5,
        "米诺陶诺斯": 5,
        "梦魇牡羊": 5,
        "托尔佩顿": 5,
        "炎吼狮王": 5,
        "美杜莎": 5,
        "暴食魔兽": 5,
        "利蝎巴鲁托": 5,
        "人马射手": 5,
        "摩羯教主": 5
    }
}

目前添加了群号与cookie的session   但是启动后init@机器人没有回应  hoshino与go-cq后台也没有回复的日志   hoshino其他的功能是正常的 ，但是启动时报了一段错误 我不太理解
上方是config文件
下方是启动时报的一段

[2022-08-16 18:28:07,527 config] WARNING: Not found config of "botmanage"
[2022-08-16 18:28:07,527 config] WARNING: Not found config of "clanbattle_info"
[2022-08-16 18:28:07,527 config] WARNING: Not found config of "pcr_autocb"
[2022-08-16 18:28:07,528 config] INFO: Succeeded to load config of "groupmaster"
[2022-08-16 18:28:07,528 config] INFO: Succeeded to load config of "priconne"
[2022-08-16 18:28:07,528 config] WARNING: Not found config of "dice"
[2022-08-16 18:28:07,862 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage"
[2022-08-16 18:28:07,863 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast"
[2022-08-16 18:28:07,863 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave"
[2022-08-16 18:28:07,863 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls"
[2022-08-16 18:28:07,864 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.data_cleaner"
[2022-08-16 18:28:07,864 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert"
[2022-08-16 18:28:07,881 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.feedback"
[2022-08-16 18:28:07,882 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite"
[2022-08-16 18:28:07,882 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.billing"
[2022-08-16 18:28:07,883 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help"
[2022-08-16 18:28:07,883 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode"
[2022-08-16 18:28:07,967 nonebot] INFO: Succeeded to import "hoshino.modules.clanbattle_info.base"
[2022-08-16 18:28:07,967 nonebot] INFO: Succeeded to import "hoshino.modules.clanbattle_info.info"
[2022-08-16 18:28:07,967 nonebot] INFO: Succeeded to import "hoshino.modules.clanbattle_info.yobot"
[2022-08-16 18:28:07,968 nonebot] ERROR: Failed to import "hoshino.modules.pcr_autocb.cbsimple", error: cannot import name 'MessageSegment' from 'hoshino' (/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/__init__.py)
[2022-08-16 18:28:07,968 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/__init__.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/modules/pcr_autocb/cbsimple.py", line 14, in <module>
    from hoshino import HoshinoBot, Service, util, priv, MessageSegment
ImportError: cannot import name 'MessageSegment' from 'hoshino' (/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/__init__.py)
[2022-08-16 18:28:07,971 nonebot] INFO: Succeeded to import "hoshino.modules.pcr_autocb.dao"
[2022-08-16 18:28:07,972 nonebot] ERROR: Failed to import "hoshino.modules.pcr_autocb.auto", error: cannot import name 'MessageSegment' from 'hoshino' (/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/__init__.py)
[2022-08-16 18:28:07,972 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/__init__.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/modules/pcr_autocb/auto.py", line 10, in <module>
    from .cbsimple import *
  File "/home/ubuntu/bot/pcr/hoshinoBot/HoshinoBot/hoshino/modules/pcr_autocb/cbsimple.py", line 14, in <module>
    from hoshino import HoshinoBot, Service, util, priv, MessageSegment

**Comment by Mysteriousmiko** [comment]
推测是hoshino本体更新了，MessageSegment没有被导入，可以参考[1](https://github.com/yoooowi/pcr_autocb/issues/18#issuecomment-1166202602)和[2](https://github.com/yoooowi/pcr_autocb/issues/18#issuecomment-1166215677)

**Comment by yimierxingweisika** [comment]
> 

感谢 用您这个方法已经解决
