### ISSUE TITLE
boss变更报错可能是什么原因

### ISSUE THREAD

**Issue by Qielanyinyin** [yoooowi/pcr_autocb#9]
[2021-12-25 14:50:42,063 clanbattle_simple] INFO: boss变更
[2021-12-25 14:50:42,064 cb-automission] ERROR: <class 'aiocqhttp.exceptions.ApiNotAvailable'> occured when doing scheduled job bossupdater.
[2021-12-25 14:50:42,064 cb-automission] ERROR:
Traceback (most recent call last):
  File "C:\bot\HoshinoBot-master\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\bot\HoshinoBot-master\hoshino\modules\pcr_autocb\auto.py", line 87, in bossupdater
    await update()
  File "C:\bot\HoshinoBot-master\hoshino\modules\pcr_autocb\auto.py", line 205, in update
    await update_boss(boss, lap, send_msg=True)
  File "C:\bot\HoshinoBot-master\hoshino\modules\pcr_autocb\cbsimple.py", line 104, in update_boss
    await bot.send_group_msg(group_id=group_id, message=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 199, in call_action
    raise ApiNotAvailable
aiocqhttp.exceptions.ApiNotAvailable

**Comment by yoooowi** [comment]
看上去是`send_group_msg`这个方法调用失败了，其他消息能正常发送吗？

**Comment by Qielanyinyin** [comment]
这个报错每2分钟检测boss更新时就会出现

使用@bot+init后，每两分钟的boss检测正常触发了
[2021-12-29 11:31:20,886 cb-automission] INFO: Scheduled job bossupdater start.
[2021-12-29 11:31:21,325 cb-automission] INFO: Scheduled job bossupdater completed.

但是一旦boss发生更换，还是会报错
[2021-12-29 11:33:21,391 clanbattle_simple] INFO: boss变更
[2021-12-29 11:33:21,407 cb-automission] ERROR: <class 'aiocqhttp.exceptions.ApiNotAvailable'> occured when doing scheduled job bossupdater.
[2021-12-29 11:33:21,407 cb-automission] ERROR:
Traceback (most recent call last):
  File "C:\bot\HoshinoBot-master\hoshino\service.py", line 349, in wrapper
    ret = await func()
  File "C:\bot\HoshinoBot-master\hoshino\modules\pcr_autocb\auto.py", line 88, in bossupdater
    await update()
  File "C:\bot\HoshinoBot-master\hoshino\modules\pcr_autocb\auto.py", line 206, in update
    await update_boss(boss, lap, send_msg=True)
  File "C:\bot\HoshinoBot-master\hoshino\modules\pcr_autocb\cbsimple.py", line 107, in update_boss
    await bot.send_group_msg(group_id=group_id, message=msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 199, in call_action
    raise ApiNotAvailable
aiocqhttp.exceptions.ApiNotAvailable

**Comment by yoooowi** [comment]
用的是什么版本的cqhttp？

**Comment by Qielanyinyin** [comment]
aiocqhttp==1.2.5

**Comment by yoooowi** [comment]
1. 看看数据库里面的boss是不是最新的
2. 你的onebot客户端是什么？如果是按照pcrbot.com的教程来部署的话应该是go-cqhttp? 版本是什么？
3. 可以试一下添加下面的代码，看看能不能正常运作
```python
@sv.on_fullmatch("复读")
async def test_repeat(bot, ev):
    await bot.send_group_msg(group_id=group_id, message="复读")
```

**Comment by Qielanyinyin** [comment]
我添加了模块dataclsses==0.6后，可以正常报boss更新了。不知道是不是这个模块原因。
之前搭建攻略里是给的0.8版本，py3.8又不能装0.8，就一直没装这个模块、今天想起来装了个0.6版本。

**Comment by Qielanyinyin** [comment]
好像跟dataclasses无关，好像和添加上面的“复读”测试代码有。
bot卡主，重启后，又开始报错。
既然出现了成功的例子，我正在尝试能想到的可能性。

**Comment by yoooowi** [comment]
能具体描述一下卡住是什么意思吗？发送”复读“bot是否有回应？log内容是什么？

**Comment by Qielanyinyin** [comment]
> 能具体描述一下卡住是什么意思吗？发送”复读“bot是否有回应？log内容是什么？
bot窗口卡在某句不再继续“执行”，不回应任何消息。go-cqhttp窗口能正常记录群消息，也没显示断开连接。

**Comment by yoooowi** [comment]
log发一下？

**Comment by Qielanyinyin** [comment]
“复读”有回应。
没找到log文件，log是指bot的窗口显示的信息吗？
现在有事，晚上我看下。

**Comment by Qielanyinyin** [comment]
中午不知道怎么地成功报了一次哥布林，当时我是尝试预约1+挂树状态的
我把今天12-29部分的error.log截出来了

[error.log](https://github.com/yoooowi/pcr_autocb/files/7788530/error.log)

**Comment by Qielanyinyin** [comment]
试了下，当有人处于挂树状态，它就能报boss更新。我怀疑是群号设置有问题，我是将gourd里的0改成群号。

**Comment by Qielanyinyin** [comment]
就很迷，当有人处于挂树状态时，可以发送boss变更。
而且我尝试在其他群“挂树”，它也会在我设置的群里发挂树超时和boss变更。

**Comment by yoooowi** [comment]
go-cqhttp的log呢？

**Comment by Qielanyinyin** [comment]
当使用“挂树”后，一切功能就能正常使用了，包括boss变更

今天注意到挂树时，后台有这样一段，不知道有没有联系
[2021-12-30 20:29:17,956 clanbattle_simple] INFO: Message -30420926 triggered climb_tree.
C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\util.py:166: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tz.localize(datetime_, is_dst=None)
[2021-12-30 20:29:17,956 clanbattle_simple] INFO: 565547657上树
[2021-12-30 20:29:18,306 nonebot] INFO: Message -30420926 is ignored
